In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [ ]:
!git clone "https://github.com/AsharZafar/ML.git"

fatal: destination path 'ML' already exists and is not an empty directory.


In [ ]:
df=pd.read_csv("/content/ML/Naive bias/titanic (1).csv")
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [ ]:
df.drop(["PassengerId", "Name" , "SibSp", "Parch", "Ticket", "Cabin", "Embarked"], axis=1,inplace=True)

In [ ]:
target=df.Survived
Inputs=df.drop(["Survived"],axis=1)

In [ ]:
dummies=pd.get_dummies(Inputs.Sex)
dummies.head()

female   male
0   False   True
1    True  False
2    True  False
3    True  False
4   False   True

In [ ]:

Inputs =pd.concat([Inputs,dummies],axis=1)
Inputs.head()

Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False
3       1  female  35.0  53.1000    True  False
4       3    male  35.0   8.0500   False   True

In [ ]:

Inputs.drop("Sex",axis=1,inplace=True)
Inputs.head()

Pclass   Age     Fare  female   male
0       3  22.0   7.2500   False   True
1       1  38.0  71.2833    True  False
2       3  26.0   7.9250    True  False
3       1  35.0  53.1000    True  False
4       3  35.0   8.0500   False   True

In [ ]:
# checking for any null values
Inputs.columns[Inputs.isna().any()]

Index(['Age'], dtype='object')

In [ ]:
mean_age = Inputs['Age'].mean()
mean_age

29.69911764705882

In [ ]:


Inputs['Age'].fillna(Inputs['Age'].mean(),inplace=True)

In [ ]:
Inputs.head(20)

Pclass        Age     Fare  female   male
0        3  22.000000   7.2500   False   True
1        1  38.000000  71.2833    True  False
2        3  26.000000   7.9250    True  False
3        1  35.000000  53.1000    True  False
4        3  35.000000   8.0500   False   True
5        3  29.699118   8.4583   False   True
6        1  54.000000  51.8625   False   True
7        3   2.000000  21.0750   False   True
8        3  27.000000  11.1333    True  False
9        2  14.000000  30.0708    True  False
10       3   4.000000  16.7000    True  False
11       1  58.000000  26.5500    True  False
12       3  20.000000   8.0500   False   True
13       3  39.000000  31.2750   False   True
14       3  14.000000   7.8542    True  False
15       2  55.000000  16.0000    True  False
16       3   2.000000  29.1250   False   True
17       2  29.699118  13.0000   False   True
18       3  31.000000  18.0000    True  False
19       3  29.699118   7.2250    True  False

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train=train_test_split(Inputs,target)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(X_train,Y_train)
model.score(X_test,Y_test)

0.7757847533632287

In [ ]:

# for first ten samples

model.predict(X_test[:10])

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0])

In [ ]:

#probablity of this sample
model.predict_proba(X_test[:10])
#First represents not survived and other represents survived

array([[9.79112542e-01, 2.08874583e-02],
       [9.92863857e-01, 7.13614345e-03],
       [4.62223965e-06, 9.99995378e-01],
       [9.93056487e-01, 6.94351267e-03],
       [9.91767785e-01, 8.23221518e-03],
       [9.91413583e-01, 8.58641747e-03],
       [9.81336590e-01, 1.86634098e-02],
       [9.11743505e-01, 8.82564954e-02],
       [4.98038433e-02, 9.50196157e-01],
       [7.69955581e-01, 2.30044419e-01]])

# Data for spam emails

In [ ]:
df=pd.read_csv("/content/ML/Naive bias/spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.groupby("Category"). describe ()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [ ]:
df["Spam"]=df["Category"].apply(lambda X: 1 if X=="spam" else 0)

In [ ]:
df.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train=train_test_split(df.Message,df.Spam,test_size=0.2)

#Now using count vectoring techniques

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_traincount=v.fit_transform(X_train.values)
X_traincount.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
#Now applying multinomial Naive bayes
#To the data

In [ ]:
from sklearn.naive_bayes import  MultinomialNB
model= MultinomialNB()
model.fit(X_traincount,Y_train)

MultinomialNB()

Testing the model

In [ ]:
emails=["Ok","Upto 20% off on all items"]
emails_check = v.transform(emails)
predictions = model.predict(emails_check)
predictions

array([0, 0])

In [ ]:
X_testcount=v.transform(X_test)
model.score(X_testcount,Y_test)

0.9847533632286996

#insted of calling contvector and Nb we will use pipline function

In [ ]:
from sklearn.pipeline import Pipeline

Clf=Pipeline ([
("Vectorizer",CountVectorizer ()),
("Nb",MultinomialNB ())])

In [ ]:
Clf.fit(X_train, Y_train)
Clf.score(X_test,Y_test)

0.9847533632286996

In [ ]:
Clf.predict(emails)

array([0, 0])

# EXERCISE
 Use wine dataset from sklearn.datasets to classify wines into 3 categories. Load the dataset and split it into test and train. After that train the model using Gaussian and Multinominal classifier and post which model performs better. Use the trained model to perform some predictions on test data.

In [ ]:
from sklearn.datasets import load_wine
Wine=load_wine()
dir(Wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [ ]:
df=pd.DataFrame(Wine.data,columns=Wine.feature_names)
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [ ]:
df["target"]=Wine.target
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(df.drop("target",axis=1),df.target,test_size=0.2)

In [ ]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB
model1=GaussianNB()
model2=MultinomialNB()


model1.fit(X_train,Y_train)
model2.fit(X_train,Y_train)


Gaussian=model1.score(X_test,Y_test)
Multinomial=model2.score(X_test,Y_test)


print("score of model Gaussian is{}", Gaussian)
print("score of model Multinomial is{}", Multinomial)

score of model Gaussian is{} 0.9444444444444444
score of model Multinomial is{} 0.75
